//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMvcUI.Models.EntittyFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        [Display(Name = "Personel Adý")]
        public string Ad { get; set; }
        [Display(Name = "Personel Soyadý")]
        public string Soyad { get; set; }
        [Display(Name = "Personel Maaþý")]
        public Nullable<int> Maas { get; set; }
        [Display(Name = "Personel Doðum Tarihi")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public bool Cinsiyet { get; set; }
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
